/*
You are given three positive integers num1, num2, and num3.

The key of num1, num2, and num3 is defined as a four-digit number such that:
Initially, if any number has less than four digits, it is padded with leading zeros.
The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2, and num3.
Return the key of the three numbers without leading zeros (if any).

Example 1:
Input: num1 = 1, num2 = 10, num3 = 1000
Output: 0
Explanation:
On padding, num1 becomes "0001", num2 becomes "0010", and num3 remains "1000".
The 1st digit of the key is min(0, 0, 1).
The 2nd digit of the key is min(0, 0, 0).
The 3rd digit of the key is min(0, 1, 0).
The 4th digit of the key is min(1, 0, 0).
Hence, the key is "0000", i.e. 0.

Example 2:
Input: num1 = 987, num2 = 879, num3 = 798
Output: 777
Example 3:
Input: num1 = 1, num2 = 2, num3 = 3
Output: 1

Constraints:
1 <= num1, num2, num3 <= 9999
*/

/**
 * @param {number} num1
 * @param {number} num2
 * @param {number} num3
 * @return {number}
 */
var generateKey = function (num1, num2, num3) {
    let num1Str = num1.toString().padStart(4, '0');
    let num2Str = num2.toString().padStart(4, '0');
    let num3Str = num3.toString().padStart(4, '0');

    let minDigit1 = Math.min(Number(num1Str[0]), Number(num2Str[0]), Number(num3Str[0]));
    let minDigit2 = Math.min(Number(num1Str[1]), Number(num2Str[1]), Number(num3Str[1]));
    let minDigit3 = Math.min(Number(num1Str[2]), Number(num2Str[2]), Number(num3Str[2]));
    let minDigit4 = Math.min(Number(num1Str[3]), Number(num2Str[3]), Number(num3Str[3]));

    let key = `${minDigit1}${minDigit2}${minDigit3}${minDigit4}`;

    return parseInt(key);
};

let num1 = 987;
let num2 = 879;
let num3 = 798;
console.log(generateKey(num1, num2, num3));