'''
You are given three positive integers num1, num2, and num3.

The key of num1, num2, and num3 is defined as a four-digit number such that:
Initially, if any number has less than four digits, it is padded with leading zeros.
The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2, and num3.
Return the key of the three numbers without leading zeros (if any).

Example 1:
Input: num1 = 1, num2 = 10, num3 = 1000
Output: 0
Explanation:
On padding, num1 becomes "0001", num2 becomes "0010", and num3 remains "1000".
The 1st digit of the key is min(0, 0, 1).
The 2nd digit of the key is min(0, 0, 0).
The 3rd digit of the key is min(0, 1, 0).
The 4th digit of the key is min(1, 0, 0).
Hence, the key is "0000", i.e. 0.

Example 2:
Input: num1 = 987, num2 = 879, num3 = 798
Output: 777
Example 3:
Input: num1 = 1, num2 = 2, num3 = 3
Output: 1

Constraints:
1 <= num1, num2, num3 <= 9999
'''


class Solution(object):
    def generateKey(self, num1, num2, num3):
        """
        :type num1: int
        :type num2: int
        :type num3: int
        :rtype: int
        """
        # Convert each number to a four-digit string with leading zeros.
        num1_str = str(num1).zfill(4)
        num2_str = str(num2).zfill(4)
        num3_str = str(num3).zfill(4)

        min_digit1 = min(num1_str[0], num2_str[0], num3_str[0])
        min_digit2 = min(num1_str[1], num2_str[1], num3_str[1])
        min_digit3 = min(num1_str[2], num2_str[2], num3_str[2])
        min_digit4 = min(num1_str[3], num2_str[3], num3_str[3])

        key_str = min_digit1 + min_digit2 + min_digit3 + min_digit4

        return int(key_str)


num1 = 987
num2 = 879
num3 = 798
solution = Solution()
print(solution.generateKey(num1, num2, num3))
